-- SEGUNDA PARTE DE LA CLASE
-------------------------------
-- Crear una vista que permita conocer por cada vecino la cantidad de propiedades con superficie construida
-- y la cantidad de propiedades sin superficie construida que posee.

-- Crear un procedimiento almacenado que liste todos los vecinos y la cantidad de propiedades que posee.

-- Crear un procedimiento almacenado que a partir de un código de vecino que se envíe como parámetro liste, el tipo de 
-- propiedad, el valor, la cantidad de m2, el valor por m2 y la antigüedad de cada una de sus propiedades.

-- Crear un procedimiento que a partir de dos importes que se listen como parámetros se listen las propiedades
-- que se encuentran dentro de ese rango de precios. Listar el apellido y nombre del propietario y el tipo de propiedad.

-- Crear un procedimiento almacenado que calcule para cada vecino el 
-- impuesto anual a abonar. El impuesto se calcula
-- en base a la suma total de la valuación de todas sus propiedades. 
-- Siendo un porcentaje de dicho valor según la
-- siguiente tabla:
-- Entre $1 y $5000000: 4% de la valuación total
-- Entre $5000000 y $10000000: 2% de la valuación total
-- Más de $10000000: 1% de la valuación total