-- PRIMERA PARTE DE LA CLASE 
--------------------------------
-- Por cada tipo de propiedad, la cantidad de vecinos distintos que poseen propiedades de dicho tipo.

-- Por cada tipo de propiedad, la cantidad de vecinos que poseen propiedades de dicho tipo.

-- Listar apellido y nombres de los vecinos que tengan más de una propiedad sin superficie construida (superficie construida igual a cero)

-- Listar apellido y nombres de los vecinos que tengan alguna propiedad con superficie construida y 
-- ninguna propiedad sin superficie construida

-- Listar el vecino que disponga de la casa con mayor valor por m2.

-- Para cada vecino, listar apellido y nombre y la antigüedad menor de sus propiedades. Si un vecino no tiene
-- propiedades registradas, listar una antigüedad con valor NULL.

-- A todos los vecinos cuya sumatoria de valuación de todas sus propiedades sea mayor a $4.000.000 y
-- posean más de una propiedad se le aplicará un impuesto del 5% del valor de sus propiedades 
-- (a excepción del valor de su propiedad más cara). 
-- Listar apellido y nombre de los vecinos que deban pagar el impuesto y cuánto deberán pagar.