-- 1) La cantidad de socios

-- 2) La cantidad de actividades de equipo.

-- 3) La suma de todos los pagos realizados.

-- 4) La suma de todos los pagos en Julio de 2018.

-- 5) El promedio de costo de las actividades.

-- 6) El costo máximo de las actividades individuales.

-- 7) El pago mínimo entre todos los pagos.

-- 8) Por cada sede, mostrar la dirección y la cantidad de actividades que se realizan en ellas.

-- 9) Por cada localidad, mostrar el nombre de la localidad y la cantidad de sedes ubicadas en ellas.

-- 10) Igual al anterior, pero listar también las localidades que no tienen sedes en ellas.

-- 11) Por cada socio, listar el nombre y apellido y la cantidad de actividades que realiza cada uno.

-- 12) Igual al anterior pero listar a los socios que sólo realicen una actividad.

-- 13) Por cada socio, listar el nombre y apellido y la cantidad de pagos realizados.

-- 14) Igual al anterior pero solamente listar aquellos socios con cero cantidad de pagos realizados.

-- 15) Por cada socio, listar el nombre y apellido y el total abonado en concepto de pagos.

-- 16) Igual al anterior pero sólo listar los socios que hayan abonado más de $1000 en total en concepto de pagos.

-- 17) Por cada socio, listar el máximo monto abonado en concepto de pagos.

-- 18) La cantidad de socios que realicen alguna actividad en equipo.